apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.33.1
        name: audiobookshelf
        envFrom:
        - configMapRef:
            name: env-configmap
        volumeMounts:
        - mountPath: "/config"
          name: "audiobookshelf-storage"
          subPath: "config"
        - mountPath: "/metadata"
          name: "audiobookshelf-storage"
          subPath: "metadata"
        - mountPath: "/audiobooks"
          name: "audiobookshelf-storage"
          subPath: "audiobooks"
        - mountPath: "/podcasts"
          name: "audiobookshelf-storage"
          subPath: "podcasts"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
      volumes:
      - name: "audiobookshelf-storage"
        persistentVolumeClaim:
          claimName: "audiobookshelf-storage-pvc"

status: {}
