apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobookshelf
    spec:
      containers:
      - image: ghcr.io/advplyr/audiobookshelf
        name: audiobookshelf
          #        volumeMounts:
          #- mountPath: "/config"
          #  name: "audiobookshelf-storage"
          #- mountPath: "/metadata"
          #  name: "audiobookshelf-storage"
          #- mountPath: "/audiobooks"
          #  name: "audiobookshelf-storage"
          #- mountPath: "/podcasts"
          #  name: "audiobookshelf-storage"
          #volumes:
          #- name: "audiobookshelf-storage"
          #persistentVolumeClaim:
          #  claimName: "audiobookshelf-storage-pvc"

status: {}
