apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 13378
  selector:
    app: audiobookshelf
  type: ClusterIP
status:
  loadBalancer: {}
