apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-storage-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
