apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LkXNBeUw+qIRKC2yz1/QAho27YQY85FWsayLCpUK2QNONpdDzRATNIVBrS8FtQkX1kWle/jYyY1TNyWOBIBENc+7nvsIodXJThljbH5jQld7qBmMui7qRiy1SoEpQBmvTcMSnCXtnLYjbfJi1jL4/b8H+cNuv2l+M+CoyeceqjG3y8Y32JsfsO6z2YrFkFLS511E1qbuOPKQUs6bAOml+fCxsiocPMO1YWFhQt+lXB8YRFlE5tFxRR+VHYZ9xB3eY17WFj6S3f6FwDQce/M0/8GqTSgQrDP7xvLagLkXsV/RFEySp7cuusFaqN8=,iv:Vq8BNOMalpi+q3U5BsOpleNMrt9kIDlLmUcayjV9fmM=,tag:1x4Q1RQheE0tBsDM6WJHvA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - recipient: age1huyccwqw8ffkpeqqxpe2mr0dmjhtmg3gupedz9g9es6v7j5pcs2sfvtvda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNXZ0d3BMQUVGbHQyYmlY
            UWUvam1qdXYzbTg0MkNJZkYwUVdxSzFveDJVClJIbFdXclFNcSsvSEY1c01iTXlD
            SldIcWwwbUVReGRWazNoKzZTTE9mTTgKLS0tIC9rUkhBZ3cwSzc5czlIamFNN3JP
            c1ZLVXg5bDZPK2pCM3lJM3V5Vjd6Mk0KnOqoGFdvDmDDGw1WDmvnJZoGqrFGTuH6
            onIzMY8W+oDDbyPZIaTgvFJw/GLwE9BAKyuPd+JXKgkYbII8q6v2Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T15:53:01Z"
    mac: ENC[AES256_GCM,data:2AJ6PFnVUvvTWgI2p4sFoRYV7xQpOED25FgzKLDiOsIbBa7zwndvRZdQVzpXUjMc2nolmSGBHPQbAm+ZJFCnsLTfSW4RkzN29vRcb5BO8rltcRksvdoaF7ZCNK6nV20cIXxyWqUPFyLalyQLtp1TOUne9/GSxcwGfc5+L/4qcdI=,iv:Biz8z9WudOWmj7KCSCO5+YNvmhuyE1eADGekBoy6vPE=,tag:mD6o9NXLzJi4jArBz7UTgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
