apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:knT2qj9vNsYhBzjF,iv:o/sAAV8IIAQRvcNTCUN61kDfztgvhGsUSu2BN0CVMfI=,tag:AEL5sgmbc2shToQGfGD0Yw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:kcwqHL7qiW4=,iv:BhFgFR3Eiej6xYdP1hM+OOMbXORVzcLsKEv09gvxn88=,tag:Afng9fagDMISr48gKK8bZA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1huyccwqw8ffkpeqqxpe2mr0dmjhtmg3gupedz9g9es6v7j5pcs2sfvtvda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NTV4NnpwOFZGandMV1RP
            VjRWRTlHcEZJRDh6eHl2QkhGWjgvSnBJMTBzClFzTUdxN3BjZHRaMFVXcm5LM003
            bytvL0VzR0tFZXhDK2dHSHkyM1MyU3cKLS0tIHhKZW5WT1cwZjRtZ0VQbGZ1WWV0
            QjlDQkY5U3QvQ0h4Nk8yK2VYL2t2YkEKLuJCI3Z2FbPVOIfLcovqsxFS1VQXppDd
            KcIE/Klz6131eIY2DpzoZQN+M6y5/8fArZcvGt87pwzEueTvrf/UOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T13:26:44Z"
    mac: ENC[AES256_GCM,data:AmLf1nLpQzk7tsIAxYg1ItCtP9ABRU4yXO7qs/j4HJmTJ0l0V/o3rg2BoAdqVQSyi8MSJlobdz7pOQHVl+2alRMeToVQgaBIl6aB2o97RRAJtDbzbhxK7dUh13MqzXVVbSfp1SAEPfojrFjdjVD145sKWew0YsGuW9w3eqAyyTg=,iv:NFRvhJ+xv1vlePbetz/FN2bB69IbjIYP+ST4f3RgKuo=,tag:ZirTck0qxlErMAPyWLO+Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
