apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4Yek3d4QK1k=,iv:LSk8RYbFHRaD9PrlaA0jz+l8vIvBHtiP0z+pr9BSjSY=,tag:KoifNPmSYLF0k+TRkF2OMA==,type:str]
    user: ENC[AES256_GCM,data:TGNsmPfh1w0=,iv:eB/61Tpuyzx6p+GKTjVr1WYpeboG6kXD4OnP9RIFUAU=,tag:SK2zohY6KNOJEWVKOXoFSQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1huyccwqw8ffkpeqqxpe2mr0dmjhtmg3gupedz9g9es6v7j5pcs2sfvtvda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcDNGZm5xVDQ4d0VGVVQ2
            cmpxVHlJS3dKUmxJNUd0cU9XeUFHdlJKQkc4CllhcWhuYkg1TjVsNFM3VW9ObTZC
            bXpNeVBmd2tuSy9BRlduMXc3aVZtSkkKLS0tIFRqU2p1dkVTTXVBdWhkczVSd3lz
            VnAwbGZZZDczVXBqaDV5bGJDa3FZR1UK9wIdZ7daIqktwNwYcv935z8oZrIE2Tma
            RYpyJbbTqmKgG5xjYjoR7E+b+niisJ4iB8Z2Fm5Hbhnhxvj1qivgnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T15:27:25Z"
    mac: ENC[AES256_GCM,data:S4rKUancE+LXrDtEaaytrwU+7IgP3FwBGrfz1tZo2SyltToZ7Y7/L91PKs4DjAo0K6BUdew7q4hGzrvDYdvVugGGc2sq1bpuqr7FpGeH9l+T32ONUzVywrE8UNM06OeYISkasi+O+WidK8Y+sq6uZvrGFfv8f6XslMNUxw450w0=,iv:CMs4FYF+dYcTw8szsNxdKMjX20EoBsX0sno3+FeZlLU=,tag:HS/iHyU4+1YJdH0WKthYPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
