apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  labels:
    app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.45.0
        ports:
          - containerPort: 9090
        envFrom:
          - secretRef:
              name: linkding-container-env
        volumeMounts:
          - mountPath: "/etc/linkding/data"
            name: linkding-data
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc

